import { JobBasicInformation } from "@models/jobExperience";

export const jobExperienceList: JobBasicInformation[] = [
  {
    id: 1,
    profileImg: "/job-experience/gourmand.jpg",
    position: "Full Stack Developer",
    company: "Gourmand",
    type: "Full-time",
    startDate: "Jul 2019",
    endDate: "Dec 2019",
    briefDescription:
      "Developed a full-stack admin panel for a restaurant management system.",
    skills: [
      "PHP",
      "MYSQL",
      "VS_CODE",
      "JAVASCRIPT",
      "GITHUB",
      "CSS",
      "MVC",
      "HTML",
    ],
  },
  {
    id: 2,
    profileImg: "/job-experience/tucandera_tours.png",
    position: "Frontend Developer",
    company: "Tucandera Tours",
    type: "Full-time",
    startDate: "Feb 2020",
    endDate: "May 2021",
    briefDescription:
      "I have been working on the frontend of the company's website, which is a touristic agency.",
    skills: [
      "ILLUSTRATOR",
      "MYSQL",
      "VS_CODE",
      "GITHUB",
      "CSS",
      "TYPESCRIPT",
      "REDUX",
      "REACT",
      "HTML",
      "PHOTOSHOP",
    ],
  },
  {
    id: 3,
    profileImg: "/job-experience/cosmon.jpg",
    position: "Frontend Developer",
    company: "COSMON",
    type: "Freelance",
    startDate: "Jun 2021",
    endDate: "Nov 2021",
    briefDescription:
      "A water cooperative that provides water and sanitation services to the local community.",
    skills: [
      "ILLUSTRATOR",
      "VS_CODE",
      "JAVASCRIPT",
      "GITHUB",
      "CSS",
      "TYPESCRIPT",
      "AGILE",
      "REDUX",
      "REACT",
      "HTML",
      "PHOTOSHOP",
    ],
  },
  {
    id: 4,
    profileImg: "/job-experience/nice.jpg",
    position: "Software Engineer",
    company: "NICE Ltd",
    type: "Full-time",
    startDate: "Jun 2022",
    endDate: "Jul 2024",
    briefDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    skills: [
      "MONGODB",
      "JAVASCRIPT",
      "CSS",
      "REDUX",
      "MICROSERVICES",
      "SPRING_BOOT",
      "FIGMA",
      "HTML",
      "JIRA",
      "DOCKER",
      "VS_CODE",
      "TYPESCRIPT",
      "AGILE",
      "REACT",
      "BITBUCKET",
    ],
  },
];
